<?php

namespace ApiV1Bundle\Repository;

/**
 * DatosTurnoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DatosTurnoRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Obtiene el repositorio
     *
     * @return \Doctrine\ORM\EntityRepository
     */
    private function getRepository()
    {
        return $this->getEntityManager()->getRepository('ApiV1Bundle:DatosTurno');
    }
}

