<?php
namespace ApiV1Bundle\Repository;

/**
 * PuntoAtencionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PuntoAtencionRepository extends ApiRepository
{

    /**
     * Obtiene el repositorio
     *
     * @return \Doctrine\ORM\EntityRepository
     */
    private function getRepository()
    {
        return $this->getEntityManager()->getRepository('ApiV1Bundle:PuntoAtencion');
    }

    /**
     * Listado de puntos de atención
     *
     * @param integer $offset Cantidad de registros a saltar
     * @param integer $limit Cantidad máxima de registros a retornar
     * @return array
     */
    public function findAllPaginate($offset, $limit)
    {
        $query = $this->getRepository()->createQueryBuilder('p');
        $query->select([
            'p.id',
            'p.nombre'
        ]);
        $query->setFirstResult($offset);
        $query->setMaxResults($limit);
        $query->orderBy('p.id', 'ASC');
        return $query->getQuery()->getResult();
    }

    /**
     * Total puntos de atención
     *
     * @return integer
     * @throws \Doctrine\ORM\NoResultException
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getTotal()
    {
        $query = $this->getRepository()->createQueryBuilder('p');
        $query->select('count(p.id)');
        $total = $query->getQuery()->getSingleScalarResult();
        return (int) $total;
    }
}
