<?php
namespace ApiV1Bundle\Repository;

/**
 * VentanillaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VentanillaRepository extends ApiRepository
{

    /**
     * Obtiene el repositorio
     *
     * @return \Doctrine\ORM\EntityRepository
     */
    private function getRepository()
    {
        return $this->getEntityManager()->getRepository('ApiV1Bundle:Ventanilla');
    }

    /**
     * Listado de ventanillas por punto de atención
     *
     * @param integer $puntoAtencionId El identficador del punto de atención
     * @param integer $offset Cantidad de registros a saltar
     * @param integer $limit Cantidad máxima de registros a retornar
     * @return array
     */
    public function findAllPaginate($puntoAtencionId, $offset, $limit)
    {
        $query = $this->getRepository()->createQueryBuilder('v');
        $query->select([
            'v.id',
            'v.identificador'
        ]);
        $query->join('v.puntoAtencion', 'p');
        $query->where('p.puntoAtencionIdSnt = :puntoAtencionId');

        $query->setParameter('puntoAtencionId', $puntoAtencionId);
        $query->orderBy('v.identificador', 'ASC');
        $query->setFirstResult($offset);
        $query->setMaxResults($limit);
        return $query->getQuery()->getResult();
    }

    /**
     * Total ventanillas por punto de atención
     *
     * @param integer $puntoAtencionId El identificador del punto de atención
     * @return integer
     * @throws \Doctrine\ORM\NoResultException
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getTotal($puntoAtencionId)
    {
        $query = $this->getRepository()->createQueryBuilder('v');
        $query->select('count(v.id)');
        $query->join('v.puntoAtencion', 'p');
        $query->where('p.puntoAtencionIdSnt = :puntoAtencionId');
        $query->setParameter('puntoAtencionId', $puntoAtencionId);
        $total = $query->getQuery()->getSingleScalarResult();
        return (int) $total;
    }
}
